# fly.toml app configuration file generated for normieneko on 2023-08-29T11:12:26+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "normieneko"
primary_region = "nrt"

[build]
useVpnkit = false

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
